apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: sample-spring-boot-on-kubernetes
build:
  artifacts:
    - image: piomin/sample-spring-boot-on-kubernetes
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/mongodb-deployment.yaml
    - k8s/deployment.yaml
deploy:
  kubectl: {}
profiles:
  - name: knative
    manifests:
      rawYaml:
        - k8s/knative-service.yaml
    deploy:
      kubectl: {}
  - name: buildpacks
    build:
      artifacts:
        - image: piomin/sample-spring-boot-on-kubernetes
          buildpacks:
            builder: paketobuildpacks/builder:base
            env:
              - BP_JVM_VERSION=21
            buildpacks:
              - paketo-buildpacks/adoptium
              - paketo-buildpacks/java
