apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: sample-spring-boot-on-kubernetes
build:
  artifacts:
  - image: piomin/sample-spring-boot-on-kubernetes
    jib:
      args:
      - -Pjib
      - -DskipTests
deploy:
  kubectl:
    manifests:
      - k8s/mongodb-deployment.yaml
      - k8s/deployment.yaml
profiles:
- name: knative
  deploy:
    kubectl:
      manifests:
      - k8s/knative-service.yaml
- name: buildpacks
  build:
    artifacts:
      - image: piomin/sample-spring-boot-on-kubernetes
        buildpacks:
          builder: paketobuildpacks/builder:base
          buildpacks:
            - paketo-buildpacks/adoptium
            - paketo-buildpacks/java
          env:
            - BP_JVM_VERSION=21


