apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sample-spring-app-with-db
build:
  local:
    push: false
  artifacts:
    - image: piomin/sample-spring-app-with-db
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base:latest
        env:
          - "BP_JVM_VERSION=21"
manifests:
  helm:
    releases:
      - name: sample-spring-app-with-db
        remoteChart: spring-boot-api-app
        repo: https://piomin.github.io/helm-charts
        setValues:
          image:
            repository: piomin/sample-spring-app-with-db
            tag: latest
          envs:
            - name: DATABASE_USER
              value: spring
            - name: DATABASE_NAME
              value: spring
          extraEnvVarsSecret:
            - envVarName: DATABASE_PASS
              key: password
              name: person-db-postgresql
profiles:
  - name: postgres
    deploy:
      helm:
        releases:
          - name: person-db
            remoteChart: postgresql
            version: 16.0.1
            repo: https://charts.bitnami.com/bitnami
            wait: false
            setValues:
              auth.username: spring
              auth.database: spring
