apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: sample-spring-k8s
build:
  artifacts:
    - image: piomin/sample-spring-k8s-ch6
      jib:
        args:
          - -DskipTests
manifests:
  rawYaml:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/secret.yaml
    - k8s/rolebinding.yaml
