apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: piomin/callme-service
      jib:
        args:
          - -Pjib
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/deployment-versions.yaml
