apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgresql
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: test
          - env: stage
          - env: prod
  template:
    metadata:
      name: postgresql-{{ .env }}
    spec:
      destination:
        namespace: {{ .env }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://charts.bitnami.com/bitnami'
        targetRevision: 16.1.2
        chart: postgresql
      syncPolicy:
        automated:
          prune: true
          selfHeal: true